### ISSUE TITLE
libffi-devel's package missing in bootstrap.sh

### ISSUE THREAD

**Issue by lalmeras** [openwide-java/owsi-core-ansible#1]
For a correct behavior, libffi-devel must be added in bootstrap.sh (`yum install ... libffi-devel`).

Package may also be fixed for dnf (same package's name) and apt (I don't know the package name).

libffi-devel is a required dependency for installing ansible's dependencies.

**Comment by cgachot** [comment]
Fixed in branch rework-factored-roles
